---
title: "Homework3"
author: "Carlos Amissah"
date: "2024-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

                                            Question 1
```
Find:\s+
replace:,
```
First String,Second,1.22,3.4

Second,More Text,1.555555,2.2220

Third,x,3,124
 
I used find "\s+" which finds spaces between words and replace with a "," 
  
                                           Question 2
```
Find: (\w*), (\w*), (.*)
Replace: \2 \1 \(\3)
```
Bryan Ballif (University of Vermont)

Aaron Ellison (Harvard Forest)

Sydne Record (Bryn Mawr)

The find expression highlights each word in the string and replace them with the expression \2 \1 \(\3). The replace expression arranges the names according to last and first names, whereas the space ensures spacing between the names. The last command puts the last string in a bracket.

                                    Question 3
 ```
 Find: (\w+[^0-9]*\w)
 Replace:\1\n
 ```
 0001 Georgia Horseshoe.mp3

 0002 Billy In The Lowground.mp3
 
 0003 Winder Slide.mp3
 
 0004 Walking Cane.mp3
 
I used the find expression to highlight the text of interest and replaced it with "\1\n". The expression "\w+" selected the set of texts (either numerical or words) whereas the expression [^0-9]*highlight every other word format except numerical values. The "\w" selected the remaining numerical value.
I placed the eexpression in parenthesis so that I can wrap it as one entity. The "\1" expression took the wrapped entity and the "\n" expression break the line from that point pushing every other sentence on that role to the next line.  
 

                                          Question 4
```
Find: ([^0-9]*)(\d+)(.*)
Replace:\1\3\2
```

Georgia Horseshoe_.mp30001

Billy In The Lowground_.mp30002

Winder Slide_.mp30003

Walking Cane_.mp30004

I used the find expression to highlight the text of interest and replaced it with "\1\3\2". The expression in the replace section selects the first two words and the underscore ([^0-9]*) followed by .mp3 (.*)and the four digits (\d+).

                                         Question 5
```
Find:(\w)(\w+),(\w+),(\w+).(\w),(\w+)
Replace:\1_\3,\6
```
C_pennsylvanicus,44

C_herculeanus,3

M_punctiventris,4

L_neoniger,55

The find expression highlights the entire word string and replaces it with the expression "\1_\3,\6". The expression in the replace section picks the first letter of the species name (\w),adds an underscore and the genus(\w+) followed by a comma and the last number(s)(\w+).

                                        Question 6
```
Find:(\w)(\w+),(\w{4})(\w+),(\w+).(\w),(\w+)
Replace:\1_\3,\7
```

C_penn,44

C_herc,3

M_punc,4

L_neon,55

The find expression highlights the entire word string and replaces it with the expression "\1_\3,\7". The expression in the replace section picks the first letter of the species name(\w),adds an underscore and the first four letters of the genus(\w{4}) followed by a comma and the last number(s)(\w+).

                                       Question 7
```
Find:(\w{3})(\w+),(\w{3})(\w+),(\w+).(\d),(\d+)
Replace:\1\3, \7, \5.\6
```
Campen, 44, 10.2

Camher, 3, 10.5

Myrpun, 4, 12.2

Lasneo, 55, 3.3

 The find expression highlights the entire word string and replaces it with the expression "\1\3, \7, \5.\6". The expression in the replace section merges the first three letters of the species name(\w{3}) with the first three letters of the genus(\w{3}) followed by a comma. Next,the last number(s)(\d+) from the original word string is selected, followed by a comma and the decimal number (first digit(s)(\w+), a period and the last digit(\d)). 
